### list all
GET http://localhost:8080/api/patients/
Accept: application/json

### find by id
GET http://localhost:8080/api/patients/1
Accept: application/json

### find by taj
GET http://localhost:8080/api/patients/taj/123456788
Accept: application/json

### create
POST http://localhost:8080/api/patients/
Content-Type: application/json
Accept: application/json

{
  "taj": "123456788",
  "name": "John Doe",
  "dateOfBirth": "1957-12-24",
  "email": "johndoe@example.com"
}

### update by id
PUT http://localhost:8080/api/patients/1
Content-Type: application/json
Accept: application/json

{
  "taj": "037687210",
  "name": "Jane Doe",
  "dateOfBirth": "1985-10-18",
  "email": "janedode@example.com"
}

### delete by id
DELETE  http://localhost:8080/api/patients/1

### delete all
DELETE  http://localhost:8080/api/patients/
